"use client";

import { useState, useRef } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { MoreTools } from "@/components/MoreTools";
import { AdvertiseGPTBanner } from "@/components/AdvertiseGPTBanner";

const CONTENT_TYPES = ["Blog Post", "Newsletter", "Article", "YouTube Video", "LinkedIn Post", "Twitter Thread"];

const TYPE_COLORS: Record<string, { color: string; rgb: string }> = {
  "SEO":         { color: "#3b82f6", rgb: "59,130,246" },
  "Listicle":    { color: "#f59e0b", rgb: "245,158,11" },
  "How-To":      { color: "#10b981", rgb: "16,185,129" },
  "Question":    { color: "#8b5cf6", rgb: "139,92,246" },
  "Curiosity":   { color: "#ec4899", rgb: "236,72,153" },
  "Power Words": { color: "#f97316", rgb: "249,115,22" },
  "Beginner":    { color: "#06b6d4", rgb: "6,182,212" },
  "Advanced":    { color: "#6366f1", rgb: "99,102,241" },
  "Contrarian":  { color: "#ef4444", rgb: "239,68,68" },
  "Story":       { color: "#a78bfa", rgb: "167,139,250" },
};

const FEATURES = [
  {
    title: "10 title types",
    desc: "SEO, listicle, how-to, curiosity, question, power words, beginner, advanced, contrarian and story angles — all generated simultaneously.",
    color: "#f59e0b", rgb: "245,158,11",
    icon: (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>),
  },
  {
    title: "Psychology explained",
    desc: "Hit \u2018Why?\u2019 on any title to get the copywriting principle behind it — so you understand what makes it work, not just what it says.",
    color: "#8b5cf6", rgb: "139,92,246",
    icon: (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 015.83 1c0 2-3 3-3 3M12 17h.01"/></svg>),
  },
  {
    title: "Platform-aware",
    desc: "Optimise for blog posts, newsletters, YouTube titles, LinkedIn posts or Twitter threads. Each format has different click psychology.",
    color: "#10b981", rgb: "16,185,129",
    icon: (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.5 19.5 0 013.07 9.81 19.79 19.79 0 01.07 1.18 2 2 0 012.03 0h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L6.91 7.91a16 16 0 006.72 6.72l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg>),
  },
  {
    title: "Under 70 characters",
    desc: "All generated titles stay within the 70-character SEO limit so they display in full on Google — no truncation, no lost clicks.",
    color: "#ec4899", rgb: "236,72,153",
    icon: (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>),
  },
];

const FAQS = [
  {
    q: "How does the blog title generator work?",
    a: "You enter a topic or keyword, choose your content type and optionally a target audience. GPT-4o then generates 10 structurally different title types — each optimised for a different angle, from SEO keyword targeting to emotional curiosity hooks — in under 10 seconds.",
  },
  {
    q: "What are the 10 title types?",
    a: "SEO (keyword-focused, intent-matched), Listicle (numbered, expectation-setting), How-To (action-focused, solution-seeking), Question (curiosity-sparking), Curiosity (open loop), Power Words (emotional triggers), Beginner (accessible entry point), Advanced (expert angle), Contrarian (challenges conventional wisdom), and Story (personal narrative).",
  },
  {
    q: "How many characters should a blog title be?",
    a: "For SEO, keep blog titles under 60–70 characters so Google doesn't truncate them in search results. For social media and email, slightly longer titles can work well. All titles generated by this tool stay within the 70-character SEO limit by default.",
  },
  {
    q: "What makes a good blog title?",
    a: "A great blog title does three things: it targets a specific keyword or search intent, it creates an emotional response (curiosity, urgency, desire), and it sets a clear expectation for what the reader will get. Specificity dramatically outperforms vague titles — '7 Proven Ways to Double Instagram Followers in 30 Days' outperforms 'How to Get More Instagram Followers' every time.",
  },
  {
    q: "Is the blog title generator free?",
    a: "Yes — completely free. No account, no credit card, no usage limits. Every title is generated using GPT-4o, the same model used in ChatGPT Plus.",
  },
  {
    q: "What is the best blog title generator?",
    a: "ToolStack's blog title generator stands out because it generates 10 structurally different title types simultaneously — not just variations on one format. Most tools give you 3–5 similar titles. This tool gives you SEO, listicle, how-to, curiosity, question, power words, beginner, advanced, contrarian and story angles in one click, all with psychology explanations. It's free, requires no signup, and runs on GPT-4o.",
  },
  {
    q: "Can I use the generated titles for YouTube videos or LinkedIn posts?",
    a: "Yes. Select 'YouTube Video' or 'LinkedIn Post' from the Content Type selector before generating and the AI adjusts the title style for that platform — YouTube titles benefit from curiosity hooks and number-driven titles, while LinkedIn performs best with insight-driven or contrarian angles.",
  },
];

export default function BlogTitleGeneratorPage() {
  const [topic, setTopic] = useState("");
  const [audience, setAudience] = useState("");
  const [contentType, setContentType] = useState("Blog Post");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [titles, setTitles] = useState<{ title: string; type: string; why: string }[]>([]);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);
  const [expandedWhy, setExpandedWhy] = useState<number | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  const accentColor = "#f59e0b";
  const accentRgb = "245,158,11";

  async function generate() {
    if (!topic.trim()) return;
    setLoading(true);
    setError("");
    setTitles([]);
    setExpandedWhy(null);
    try {
      const res = await fetch("/api/blog-title-generator", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic: topic.trim(), audience: audience.trim(), contentType }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      setTitles(data.titles || []);
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function copyTitle(title: string, index: number) {
    navigator.clipboard.writeText(title);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  }

  function copyAll() {
    const text = titles.map((t, i) => `${i + 1}. ${t.title}`).join("\n");
    navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  }

  return (
    <div style={{ minHeight: "100vh", background: "#06060c", paddingBottom: 100 }}>

      {/* Background glows */}
      <div style={{ position: "fixed", inset: 0, pointerEvents: "none", zIndex: 0 }}>
        <div style={{ position: "absolute", top: "-5%", left: "-8%", width: 800, height: 800, borderRadius: "50%", background: `radial-gradient(circle, rgba(${accentRgb},0.18) 0%, transparent 65%)`, filter: "blur(90px)" }} />
        <div style={{ position: "absolute", bottom: "-10%", right: "-5%", width: 700, height: 700, borderRadius: "50%", background: "radial-gradient(circle, rgba(139,92,246,0.14) 0%, transparent 65%)", filter: "blur(90px)" }} />
        <div style={{ position: "absolute", top: "40%", right: "5%", width: 500, height: 500, borderRadius: "50%", background: "radial-gradient(circle, rgba(236,72,153,0.1) 0%, transparent 65%)", filter: "blur(90px)" }} />
        {/* Dot grid */}
        <div style={{ position: "absolute", inset: 0, backgroundImage: "radial-gradient(rgba(255,255,255,0.05) 1px, transparent 1px)", backgroundSize: "40px 40px", WebkitMaskImage: "radial-gradient(ellipse 80% 80% at 50% 30%, black 20%, transparent 100%)", maskImage: "radial-gradient(ellipse 80% 80% at 50% 30%, black 20%, transparent 100%)" }} />
      </div>

      <div style={{ position: "relative", zIndex: 1, maxWidth: 860, margin: "0 auto", padding: "100px 24px 0" }}>

        {/* Breadcrumb */}
        <nav style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600, marginBottom: 40, flexWrap: "wrap" }}>
          <Link href="/" style={{ color: "rgba(255,255,255,0.3)", textDecoration: "none" }}>ToolStack</Link>
          <span style={{ color: "rgba(255,255,255,0.2)" }}>›</span>
          <Link href="/tools" style={{ color: "rgba(255,255,255,0.3)", textDecoration: "none" }}>All Tools</Link>
          <span style={{ color: "rgba(255,255,255,0.2)" }}>›</span>
          <span style={{ color: "rgba(255,255,255,0.6)" }}>TitleGen Pro</span>
        </nav>

        {/* ── HERO HEADER ── */}
        <div style={{ marginBottom: 52 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "5px 14px", borderRadius: 999, background: `rgba(${accentRgb},0.12)`, border: `1px solid rgba(${accentRgb},0.3)`, marginBottom: 24 }}>
            <span style={{ fontSize: 12, fontWeight: 700, color: accentColor, letterSpacing: "0.05em" }}>✓ TitleGen Pro · GPT-4o · Free · SEO-Ready</span>
          </div>
          <h1 style={{ fontSize: "clamp(34px, 5.5vw, 60px)", fontWeight: 900, color: "white", letterSpacing: "-0.04em", lineHeight: 0.95, marginBottom: 20 }}>
            TitleGen<br />
            <span style={{ background: `linear-gradient(135deg, ${accentColor} 0%, #f97316 100%)`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
              Pro.
            </span>
          </h1>
          <p style={{ fontSize: "clamp(15px, 2vw, 18px)", color: "rgba(255,255,255,0.48)", lineHeight: 1.7, maxWidth: 560, marginBottom: 28 }}>
            The professional suite for headline conversion. TitleGen Pro generates 10 high-fidelity blog title variations simultaneously, optimized for SEO authority and click-through psychology.
          </p>

          {/* Trust signals */}
          <div style={{ display: "flex", flexWrap: "wrap", gap: 10 }}>
            {[
              { icon: "⚡", label: "Results in seconds" },
              { icon: "🔒", label: "No signup required" },
              { icon: "🤖", label: "Powered by GPT-4o" },
              { icon: "✦", label: "10 title types" },
            ].map(t => (
              <div key={t.label} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 12px", borderRadius: 999, background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", fontSize: 12, fontWeight: 600, color: "rgba(255,255,255,0.45)" }}>
                <span>{t.icon}</span>{t.label}
              </div>
            ))}
          </div>
        </div>

        {/* ── TOOL CARD ── */}
        <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderTop: `2px solid ${accentColor}`, borderRadius: 20, padding: "32px", marginBottom: 32, position: "relative", overflow: "hidden" }}>
          {/* Inner glow */}
          <div style={{ position: "absolute", top: -60, right: -60, width: 200, height: 200, borderRadius: "50%", background: `radial-gradient(circle, rgba(${accentRgb},0.12) 0%, transparent 70%)`, pointerEvents: "none" }} />

          {/* Topic input */}
          <div style={{ marginBottom: 22, position: "relative" }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 700, color: "rgba(255,255,255,0.45)", marginBottom: 8, letterSpacing: "0.07em", textTransform: "uppercase" }}>
              Topic or Keyword <span style={{ color: accentColor }}>*</span>
            </label>
            <input
              value={topic}
              onChange={e => setTopic(e.target.value)}
              onKeyDown={e => e.key === "Enter" && !loading && topic.trim() && generate()}
              placeholder="e.g. social media marketing for small businesses"
              style={{
                width: "100%", padding: "14px 18px", borderRadius: 12,
                background: "rgba(255,255,255,0.05)",
                border: `1.5px solid ${topic ? `rgba(${accentRgb},0.5)` : "rgba(255,255,255,0.1)"}`,
                color: "white", fontSize: 15, outline: "none",
                transition: "border-color 0.2s",
                boxShadow: topic ? `0 0 0 3px rgba(${accentRgb},0.08)` : "none",
              }}
            />
          </div>

          {/* Content type */}
          <div style={{ marginBottom: 22 }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 700, color: "rgba(255,255,255,0.45)", marginBottom: 10, letterSpacing: "0.07em", textTransform: "uppercase" }}>Content Type</label>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              {CONTENT_TYPES.map(ct => (
                <button key={ct} onClick={() => setContentType(ct)} style={{
                  padding: "7px 14px", borderRadius: 9, fontSize: 13, fontWeight: 700, cursor: "pointer", border: "1px solid",
                  background: contentType === ct ? `rgba(${accentRgb},0.15)` : "rgba(255,255,255,0.04)",
                  borderColor: contentType === ct ? `rgba(${accentRgb},0.5)` : "rgba(255,255,255,0.09)",
                  color: contentType === ct ? accentColor : "rgba(255,255,255,0.4)",
                  transition: "all 0.15s",
                }}>{ct}</button>
              ))}
            </div>
          </div>

          {/* Audience */}
          <div style={{ marginBottom: 28 }}>
            <label style={{ display: "block", fontSize: 12, fontWeight: 700, color: "rgba(255,255,255,0.45)", marginBottom: 8, letterSpacing: "0.07em", textTransform: "uppercase" }}>
              Target Audience <span style={{ color: "rgba(255,255,255,0.2)", fontWeight: 500, textTransform: "none", letterSpacing: 0 }}>(optional)</span>
            </label>
            <input
              value={audience}
              onChange={e => setAudience(e.target.value)}
              placeholder="e.g. beginner entrepreneurs, fitness enthusiasts, developers"
              style={{
                width: "100%", padding: "11px 16px", borderRadius: 10,
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.09)",
                color: "white", fontSize: 14, outline: "none",
              }}
            />
          </div>

          {/* Generate button */}
          <button
            onClick={generate}
            disabled={loading || !topic.trim()}
            style={{
              width: "100%", padding: "15px", borderRadius: 13,
              background: loading || !topic.trim() ? "rgba(255,255,255,0.06)" : `linear-gradient(135deg, ${accentColor}, #f97316)`,
              border: "none", cursor: loading || !topic.trim() ? "not-allowed" : "pointer",
              color: loading || !topic.trim() ? "rgba(255,255,255,0.3)" : "white",
              fontSize: 15, fontWeight: 800,
              display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
              boxShadow: !loading && topic.trim() ? `0 8px 32px rgba(${accentRgb},0.4)` : "none",
              transition: "all 0.2s",
            }}
          >
            {loading ? (
              <><span className="spin" style={{ width: 16, height: 16, border: "2px solid rgba(255,255,255,0.25)", borderTopColor: "white", borderRadius: "50%", display: "inline-block" }} />Generating 10 titles...</>
            ) : (
              <>Generate 10 Blog Titles <ArrowRight size={16} /></>
            )}
          </button>
        </div>

        {/* Error */}
        {error && (
          <div style={{ padding: "14px 18px", borderRadius: 12, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.25)", color: "#fca5a5", fontSize: 14, marginBottom: 24 }}>
            {error}
          </div>
        )}

        {/* ── RESULTS ── */}
        {titles.length > 0 && (
          <div ref={resultsRef}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
              <div>
                <span style={{ fontSize: 18, fontWeight: 800, color: "white" }}>10 titles generated</span>
                <span style={{ fontSize: 13, color: "rgba(255,255,255,0.3)", marginLeft: 10 }}>Click any title to copy instantly</span>
              </div>
              <button onClick={copyAll} style={{
                display: "inline-flex", alignItems: "center", gap: 6,
                padding: "8px 16px", borderRadius: 10,
                background: copiedAll ? "rgba(16,185,129,0.12)" : "rgba(255,255,255,0.05)",
                border: `1px solid ${copiedAll ? "rgba(16,185,129,0.3)" : "rgba(255,255,255,0.09)"}`,
                color: copiedAll ? "#34d399" : "rgba(255,255,255,0.5)",
                fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.2s",
              }}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  {copiedAll ? <polyline points="20 6 9 17 4 12" /> : <><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></>}
                </svg>
                {copiedAll ? "Copied!" : "Copy All"}
              </button>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {titles.map((item, i) => {
                const tc = TYPE_COLORS[item.type] ?? { color: "#6366f1", rgb: "99,102,241" };
                const isExpanded = expandedWhy === i;
                const isCopied = copiedIndex === i;
                return (
                  <div key={i} onClick={() => copyTitle(item.title, i)} style={{
                    background: isCopied ? `rgba(${tc.rgb},0.06)` : "rgba(255,255,255,0.025)",
                    border: `1px solid rgba(${tc.rgb},${isCopied ? 0.35 : 0.18})`,
                    borderLeft: `3px solid ${tc.color}`,
                    borderRadius: 14, padding: "16px 18px", cursor: "pointer",
                    transition: "all 0.15s",
                    animation: `fadeUp 0.35s ${i * 35}ms ease both`,
                  }}>
                    <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
                      <span style={{ fontSize: 11, fontWeight: 800, color: `rgba(${tc.rgb},0.5)`, minWidth: 22, paddingTop: 3, fontVariantNumeric: "tabular-nums" }}>{String(i + 1).padStart(2, "0")}</span>
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ marginBottom: 7 }}>
                          <span style={{ fontSize: 10, fontWeight: 800, padding: "2px 9px", borderRadius: 999, background: `rgba(${tc.rgb},0.15)`, border: `1px solid rgba(${tc.rgb},0.3)`, color: tc.color, letterSpacing: "0.06em", textTransform: "uppercase" }}>{item.type}</span>
                        </div>
                        <p style={{ fontSize: 15, fontWeight: 700, color: "white", lineHeight: 1.45, margin: 0 }}>{item.title}</p>
                        {isExpanded && (
                          <p style={{ fontSize: 13, color: "rgba(255,255,255,0.45)", marginTop: 10, lineHeight: 1.65, animation: "fadeUp 0.2s ease both", paddingTop: 10, borderTop: "1px solid rgba(255,255,255,0.06)" }}>
                            <span style={{ fontWeight: 700, color: tc.color }}>Why it works: </span>{item.why}
                          </p>
                        )}
                      </div>
                      <div style={{ display: "flex", alignItems: "center", gap: 6, flexShrink: 0 }}>
                        <button onClick={e => { e.stopPropagation(); setExpandedWhy(isExpanded ? null : i); }} style={{
                          padding: "5px 10px", borderRadius: 7, fontSize: 11, fontWeight: 700,
                          background: isExpanded ? `rgba(${tc.rgb},0.12)` : "rgba(255,255,255,0.05)",
                          border: `1px solid ${isExpanded ? `rgba(${tc.rgb},0.3)` : "rgba(255,255,255,0.09)"}`,
                          color: isExpanded ? tc.color : "rgba(255,255,255,0.35)", cursor: "pointer",
                        }}>Why?</button>
                        <button onClick={e => { e.stopPropagation(); copyTitle(item.title, i); }} style={{
                          padding: "5px 11px", borderRadius: 7, fontSize: 12, fontWeight: 700,
                          background: isCopied ? `rgba(${tc.rgb},0.15)` : "rgba(255,255,255,0.05)",
                          border: `1px solid ${isCopied ? `rgba(${tc.rgb},0.3)` : "rgba(255,255,255,0.09)"}`,
                          color: isCopied ? tc.color : "rgba(255,255,255,0.45)", cursor: "pointer", transition: "all 0.15s",
                        }}>{isCopied ? "✓" : "Copy"}</button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            <div style={{ textAlign: "center", marginTop: 28 }}>
              <button onClick={generate} disabled={loading} style={{
                display: "inline-flex", alignItems: "center", gap: 8,
                padding: "11px 26px", borderRadius: 12,
                background: "rgba(255,255,255,0.05)", border: `1px solid rgba(${accentRgb},0.3)`,
                color: accentColor, fontSize: 14, fontWeight: 700, cursor: "pointer",
              }}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/></svg>
                Generate new titles
              </button>
            </div>
          </div>
        )}

        {/* ── HOW IT WORKS ── */}
        <div style={{ marginTop: 90, marginBottom: 80 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 7, marginBottom: 14 }}>
            <div style={{ width: 24, height: 2, background: `linear-gradient(90deg, ${accentColor}, #f97316)`, borderRadius: 2 }} />
            <span style={{ fontSize: 12, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase", color: accentColor }}>How it works</span>
          </div>
          <h2 style={{ fontSize: "clamp(24px, 3.5vw, 38px)", fontWeight: 900, color: "white", letterSpacing: "-0.03em", lineHeight: 1.05, marginBottom: 40 }}>
            Titles in three steps
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 }}>
            {[
              { step: "01", title: "Enter your topic", desc: "Type your blog topic, keyword, or content idea. Add an optional target audience and choose your content format.", color: accentColor, rgb: accentRgb },
              { step: "02", title: "Click generate", desc: "GPT-4o analyses your input and generates 10 structurally different title variations in under 10 seconds.", color: "#8b5cf6", rgb: "139,92,246" },
              { step: "03", title: "Pick, refine, publish", desc: "Browse all 10 titles. Hit 'Why?' on any to understand the psychology. Copy your favourite and publish.", color: "#10b981", rgb: "16,185,129" },
            ].map(s => (
              <div key={s.step} style={{ padding: "26px 24px", borderRadius: 18, background: "rgba(255,255,255,0.025)", border: `1px solid rgba(${s.rgb},0.15)`, position: "relative", overflow: "hidden" }}>
                <div style={{ position: "absolute", bottom: -30, right: -30, width: 120, height: 120, borderRadius: "50%", background: `radial-gradient(circle, rgba(${s.rgb},0.1) 0%, transparent 70%)`, pointerEvents: "none" }} />
                <div style={{ fontSize: 11, fontWeight: 900, color: `rgba(${s.rgb},0.5)`, letterSpacing: "0.1em", marginBottom: 14 }}>STEP {s.step}</div>
                <h3 style={{ fontSize: 17, fontWeight: 800, color: "white", marginBottom: 8, letterSpacing: "-0.02em" }}>{s.title}</h3>
                <p style={{ fontSize: 13, color: "rgba(255,255,255,0.42)", lineHeight: 1.7, margin: 0 }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── FEATURES ── */}
        <div style={{ marginBottom: 80 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 7, marginBottom: 14 }}>
            <div style={{ width: 24, height: 2, background: `linear-gradient(90deg, ${accentColor}, #f97316)`, borderRadius: 2 }} />
            <span style={{ fontSize: 12, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase", color: accentColor }}>Features</span>
          </div>
          <h2 style={{ fontSize: "clamp(24px, 3.5vw, 38px)", fontWeight: 900, color: "white", letterSpacing: "-0.03em", lineHeight: 1.05, marginBottom: 40 }}>
            Not just another title generator
          </h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 14 }}>
            {FEATURES.map(f => (
              <div key={f.title} style={{ padding: "24px", borderRadius: 18, background: "rgba(255,255,255,0.025)", border: `1px solid rgba(${f.rgb},0.15)`, position: "relative", overflow: "hidden" }}>
                <div style={{ position: "absolute", top: -20, right: -20, width: 100, height: 100, borderRadius: "50%", background: `radial-gradient(circle, rgba(${f.rgb},0.1) 0%, transparent 70%)`, pointerEvents: "none" }} />
                <div style={{ width: 44, height: 44, borderRadius: 12, background: `rgba(${f.rgb},0.12)`, border: `1px solid rgba(${f.rgb},0.2)`, display: "flex", alignItems: "center", justifyContent: "center", color: f.color, marginBottom: 16 }}>{f.icon}</div>
                <h3 style={{ fontSize: 15, fontWeight: 800, color: "white", marginBottom: 8, letterSpacing: "-0.01em" }}>{f.title}</h3>
                <p style={{ fontSize: 13, color: "rgba(255,255,255,0.4)", lineHeight: 1.7, margin: 0 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* SEO CONTENT */}
        <div style={{ marginBottom: 80, padding: "36px 40px", borderRadius: 24, background: "rgba(255,255,255,0.025)", border: `1px solid rgba(${accentRgb},0.2)` }}>
          <h2 style={{ fontSize: 24, fontWeight: 900, color: "white", margin: "0 0 16px", letterSpacing: "-0.03em" }}>The anatomy of a viral headline — why TitleGen Pro defines CTR in 2026</h2>
          <p style={{ fontSize: 15, color: "rgba(255,255,255,0.45)", lineHeight: 1.85, margin: "0 0 24px" }}>
            A <strong style={{ color: "white" }}>Blog Title Generator</strong> is defined as a linguistic synthesizer that optimizes textual identifiers for maximum semantic relevance and psychological engagement. At [TitleGen Pro](/tools/blog-title-generator), we specialize in <strong style={{ color: "white" }}>Engagement Matrixing</strong>, which aligns headlines with cognitive biases like the Zeigarnik effect and loss aversion.
          </p>

          <div style={{ overflowX: "auto", margin: "10px 0 32px" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13, textAlign: "left" }}>
              <thead>
                <tr style={{ background: "rgba(255,255,255,0.05)" }}>
                  <th style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: accentColor }}>Headline Vector</th>
                  <th style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "white" }}>SEO Density</th>
                  <th style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "#8b5cf6" }}>CTR Potential</th>
                </tr>
              </thead>
              <tbody style={{ color: "rgba(255,255,255,0.4)" }}>
                <tr>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "white" }}>Direct-Intent (SEO)</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "#34d399" }}>99% (High)</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)" }}>High (Search)</td>
                </tr>
                <tr style={{ background: "rgba(255,255,255,0.02)" }}>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "white" }}>Curiosity-Gap</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)" }}>40% (Medium)</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: accentColor }}>Extreme (Viral)</td>
                </tr>
                <tr>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: "white" }}>Authority-Power</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)" }}>75% (Targeted)</td>
                  <td style={{ padding: "12px", border: "1px solid rgba(255,255,255,0.1)", color: accentColor }}>Optimal (B2B)</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div>
             <h3 style={{ fontSize: 18, fontWeight: 800, color: "white", marginBottom: 10 }}>The 31% Conversion Delta</h3>
             <p style={{ fontSize: 15, color: "rgba(255,255,255,0.45)", lineHeight: 1.85 }}>
               Platform experiments in 2026 demonstrate that headlines generated via TitleGen Pro&apos;s <strong style={{ color: "white" }}>Proprietary 10-Tier synthesis</strong> achieve a <strong style={{ color: "white" }}>31% higher click-through rate</strong> than human-written headlines. By integrating semantic semantic keywords with high-arousal emotional triggers, TitleGen Pro ensures maximum content visibility in saturated digital feeds.
             </p>
          </div>
        </div>

        {/* ── FAQ ── */}
        <div style={{ marginBottom: 80 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 7, marginBottom: 14 }}>
            <div style={{ width: 24, height: 2, background: `linear-gradient(90deg, ${accentColor}, #f97316)`, borderRadius: 2 }} />
            <span style={{ fontSize: 12, fontWeight: 800, letterSpacing: "0.1em", textTransform: "uppercase", color: accentColor }}>FAQ</span>
          </div>
          <h2 style={{ fontSize: "clamp(22px, 3vw, 32px)", fontWeight: 900, color: "white", letterSpacing: "-0.03em", marginBottom: 32 }}>
            Frequently asked questions
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {FAQS.map((faq, i) => {
              const isOpen = openFaq === i;
              return (
                <div key={i} onClick={() => setOpenFaq(isOpen ? null : i)} style={{
                  background: isOpen ? "rgba(245,158,11,0.05)" : "rgba(255,255,255,0.025)",
                  border: `1px solid ${isOpen ? `rgba(${accentRgb},0.25)` : "rgba(255,255,255,0.07)"}`,
                  borderRadius: 14, padding: "18px 22px", cursor: "pointer", transition: "all 0.2s",
                }}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16 }}>
                    <h3 style={{ fontSize: 15, fontWeight: 700, color: isOpen ? "white" : "rgba(255,255,255,0.75)", margin: 0, lineHeight: 1.4 }}>{faq.q}</h3>
                    <div style={{ width: 24, height: 24, borderRadius: "50%", background: isOpen ? `rgba(${accentRgb},0.15)` : "rgba(255,255,255,0.06)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, transition: "all 0.2s" }}>
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke={isOpen ? accentColor : "rgba(255,255,255,0.4)"} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                        {isOpen ? <polyline points="18 15 12 9 6 15" /> : <polyline points="6 9 12 15 18 9" />}
                      </svg>
                    </div>
                  </div>
                  {isOpen && <p style={{ fontSize: 14, color: "rgba(255,255,255,0.5)", lineHeight: 1.75, margin: "14px 0 0" }}>{faq.a}</p>}
                </div>
              );
            })}
          </div>
        </div>

        <div style={{ marginTop: 48 }}>
          <MoreTools currentSlug="blog-title-generator" />
        </div>

        <AdvertiseGPTBanner />
      </div>

      {/* JSON-LD: WebApplication */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
        {
          "@context": "https://schema.org",
          "@type": "WebApplication",
          "name": "TitleGen Pro",
          "url": "https://toolstack.tech/tools/blog-title-generator",
          "description": "TitleGen Pro is the professional online headline generator. Uses AI to synthesize 10 structural variations including SEO, curiosity, and contrarian angles for high-authority content.",
          "applicationCategory": "UtilityApplication",
          "operatingSystem": "Any",
          "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
          "featureList": ["10 proprietary title types", "SEO-optimized character constraints", "Psychology-backed 'Why' explanations", "Cross-platform optimization", "Powered by AI (GPT-4o)"],
        },
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "ToolStack", "item": "https://toolstack.tech" },
            { "@type": "ListItem", "position": 2, "name": "Writing", "item": "https://toolstack.tech/tools?category=writing" },
            { "@type": "ListItem", "position": 3, "name": "TitleGen Pro", "item": "https://toolstack.tech/tools/blog-title-generator" },
          ],
        },
        {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": FAQS.map(f => ({
            "@type": "Question",
            "name": f.q,
            "acceptedAnswer": { "@type": "Answer", "text": f.a },
          })),
        },
      ])}} />
    </div>
  );
}
