"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import { Play, Copy, Download, Check, FileText, Clock, AlignLeft, Hash } from "lucide-react";
import { MoreTools } from "@/components/MoreTools";
import { AdvertiseGPTBanner } from "@/components/AdvertiseGPTBanner";

const FAQS = [
  { q: "What is a YouTube transcript?", a: "A YouTube transcript is the full text version of everything spoken in a video. YouTube generates these automatically using speech recognition, or creators can upload their own captions. Transcripts make video content searchable, accessible, and reusable — you can turn any lecture, podcast, or tutorial into readable text in seconds." },
  { q: "Does this work on all YouTube videos?", a: "It works on any public YouTube video that has captions enabled — either auto-generated by YouTube or manually uploaded by the creator. Private videos and videos where the creator has disabled captions cannot be transcribed. Most public videos (especially English-language content) have auto-generated captions available." },
  { q: "What is the best free YouTube transcript extractor?", a: "ToolStack's YouTube Transcript Extractor is the best free option because it requires no login, has no usage limits, and outputs clean Markdown — not raw text. Most competitors (Tactiq, Notta, Glasp) require a Google account login or limit the number of transcripts per day. ToolStack gives you unlimited extractions with no account needed." },
  { q: "What does Markdown output mean?", a: "Markdown is a lightweight formatting language used by developers, writers, and content creators. Our tool formats the transcript with the video title as a heading, channel name, URL, and the transcript itself — ready to paste into Notion, Obsidian, a blog post, or any Markdown editor. It is far more useful than raw plain text." },
  { q: "Can I get timestamps in the transcript?", a: "Yes — toggle the Timestamps switch before extracting and every line will be prefixed with the time it appears in the video (e.g. [1:23] Hello and welcome). This makes it easy to jump to specific moments. Turn timestamps off for a clean, readable version without time codes." },
  { q: "Is there a length limit on videos?", a: "No — there is no length limit. You can extract transcripts from 2-minute clips or 3-hour lectures. Longer videos produce longer transcripts, but the extraction speed remains fast regardless of video length because we fetch captions directly rather than processing audio." },
  { q: "How do I use a YouTube transcript to create content?", a: "A YouTube transcript is a goldmine for content repurposing. Paste it into the ToolStack Text Summarizer to get a blog-post-ready summary. Use the Paraphrasing Tool to rewrite sections in your own voice. Run it through the Blog Title Generator to find article angles. One video can become a blog post, a newsletter, and a Twitter thread — all for free." },
];

export default function YoutubeTranscriptPage() {
  const [url, setUrl] = useState("");
  const [timestamps, setTimestamps] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<{ markdown: string; title: string; author: string; videoId: string; wordCount: number; readMinutes: number } | null>(null);
  const [copied, setCopied] = useState(false);
  const [visible, setVisible] = useState(false);

  const extract = useCallback(async () => {
    if (!url.trim()) return;
    setLoading(true);
    setError("");
    setResult(null);
    setVisible(false);
    try {
      const res = await fetch("/api/youtube-transcript", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim(), timestamps }),
      });
      const data = await res.json();
      if (!res.ok || data.error) { setError(data.error || "Failed to extract transcript."); return; }
      setResult(data);
      setTimeout(() => setVisible(true), 50);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [url, timestamps]);

  const copy = useCallback(() => {
    if (!result) return;
    navigator.clipboard.writeText(result.markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [result]);

  const download = useCallback(() => {
    if (!result) return;
    const blob = new Blob([result.markdown], { type: "text/markdown" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${result.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-transcript.md`;
    a.click();
  }, [result]);

  const card: React.CSSProperties = {
    background: "rgba(255,255,255,0.035)",
    border: "1px solid rgba(255,255,255,0.09)",
    borderRadius: 24,
    padding: "28px 32px",
    marginBottom: 16,
  };

  const badge = (color: string, bg: string): React.CSSProperties => ({
    display: "inline-flex", alignItems: "center", gap: 6,
    padding: "5px 12px", borderRadius: 999,
    background: bg, border: `1px solid ${color}`,
    fontSize: 12, fontWeight: 600, color,
  });

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
        {
          "@context": "https://schema.org",
          "@type": "WebApplication",
          "name": "YouTube Transcript Extractor",
          "description": "Extract any YouTube video transcript instantly. Download as clean Markdown with or without timestamps. Free, no login, no limits.",
          "url": "https://toolstack.tech/tools/youtube-transcript",
          "applicationCategory": "UtilityApplication",
          "operatingSystem": "Web",
          "browserRequirements": "Requires JavaScript",
          "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
          "featureList": [
            "YouTube transcript extraction",
            "Markdown formatted output",
            "Timestamp toggle",
            "Download as .md file",
            "No login or signup required",
            "Unlimited extractions",
            "Word count and read time",
          ],
        },
        {
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "ToolStack", "item": "https://toolstack.tech" },
            { "@type": "ListItem", "position": 2, "name": "Tools", "item": "https://toolstack.tech/tools" },
            { "@type": "ListItem", "position": 3, "name": "YouTube Transcript Extractor", "item": "https://toolstack.tech/tools/youtube-transcript" },
          ],
        },
        {
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": FAQS.map(f => ({
            "@type": "Question",
            "name": f.q,
            "acceptedAnswer": { "@type": "Answer", "text": f.a },
          })),
        },
      ]) }} />

      <div style={{ minHeight: "100vh", background: "#080810", paddingTop: 80 }}>

        {/* Ambient */}
        <div style={{ position: "fixed", inset: 0, pointerEvents: "none", zIndex: 0, overflow: "hidden" }}>
          <div style={{ position: "absolute", top: "-5%", left: "10%", width: 700, height: 500, background: "radial-gradient(circle, rgba(239,68,68,0.07) 0%, transparent 70%)", borderRadius: "50%" }} />
          <div style={{ position: "absolute", top: "30%", right: "5%", width: 500, height: 500, background: "radial-gradient(circle, rgba(99,102,241,0.05) 0%, transparent 70%)", borderRadius: "50%" }} />
          <div style={{ position: "absolute", bottom: "10%", left: "30%", width: 600, height: 400, background: "radial-gradient(circle, rgba(139,92,246,0.04) 0%, transparent 70%)", borderRadius: "50%" }} />
        </div>

        <div style={{ maxWidth: 860, margin: "0 auto", padding: "0 24px 100px", position: "relative", zIndex: 1 }}>

          {/* Breadcrumb */}
          <nav style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 32, fontSize: 13, color: "rgba(255,255,255,0.55)" }}>
            <Link href="/" style={{ color: "rgba(255,255,255,0.55)", textDecoration: "none" }}>ToolStack</Link>
            <span>/</span>
            <Link href="/tools" style={{ color: "rgba(255,255,255,0.55)", textDecoration: "none" }}>Tools</Link>
            <span>/</span>
            <span style={{ color: "rgba(255,255,255,0.8)" }}>YouTube Transcript</span>
          </nav>

          {/* Hero */}
          <div style={{ marginBottom: 32 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
              <div style={{ width: 48, height: 48, borderRadius: 14, background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                <Play size={24} color="#f87171" />
              </div>
              <div>
                <p style={{ fontSize: 12, fontWeight: 700, color: "rgba(239,68,68,0.8)", textTransform: "uppercase", letterSpacing: "0.08em", margin: 0 }}>YouTube Tools</p>
                <p style={{ fontSize: 12, color: "rgba(255,255,255,0.35)", margin: 0 }}>Free forever · No login</p>
              </div>
            </div>
            <h1 style={{ fontSize: "clamp(32px,5vw,48px)", fontWeight: 800, lineHeight: 1.15, margin: "0 0 14px", letterSpacing: "-0.02em" }}>
              YouTube <span style={{ background: "linear-gradient(135deg,#f87171,#ef4444)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Transcript</span> Extractor
            </h1>
            <p style={{ fontSize: 17, color: "rgba(255,255,255,0.55)", margin: "0 0 20px", lineHeight: 1.6, maxWidth: 600 }}>
              Paste any YouTube URL and get the full transcript as clean Markdown — with or without timestamps. No login. No limits. Instant.
            </p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              <span style={badge("rgba(239,68,68,0.8)", "rgba(239,68,68,0.1)")}>🎬 Any Public Video</span>
              <span style={badge("rgba(99,102,241,0.8)", "rgba(99,102,241,0.1)")}>📝 Markdown Output</span>
              <span style={badge("rgba(52,211,153,0.8)", "rgba(52,211,153,0.1)")}>✓ Free Forever</span>
              <span style={badge("rgba(251,191,36,0.8)", "rgba(251,191,36,0.1)")}>⚡ No Login</span>
            </div>
          </div>

          {/* Input card */}
          <div style={card}>
            <label style={{ display: "block", fontSize: 13, fontWeight: 700, color: "rgba(255,255,255,0.55)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>
              YouTube URL or Video ID
            </label>
            <input
              type="text"
              value={url}
              onChange={e => setUrl(e.target.value)}
              onKeyDown={e => e.key === "Enter" && extract()}
              placeholder="https://www.youtube.com/watch?v=... or video ID"
              style={{
                width: "100%", boxSizing: "border-box",
                background: "rgba(255,255,255,0.05)",
                border: "1px solid rgba(255,255,255,0.12)",
                borderRadius: 12, padding: "14px 16px",
                color: "white", fontSize: 15,
                outline: "none", marginBottom: 16,
              }}
            />

            {/* Timestamps toggle */}
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12, marginBottom: 20 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <button
                  onClick={() => setTimestamps(t => !t)}
                  aria-label="Toggle timestamps"
                  aria-pressed={timestamps}
                  style={{
                    width: 44, height: 24, borderRadius: 12,
                    background: timestamps ? "#6366f1" : "rgba(255,255,255,0.1)",
                    border: "none", cursor: "pointer", position: "relative",
                    transition: "background 0.2s",
                  }}
                >
                  <span style={{
                    position: "absolute", top: 3, left: timestamps ? 23 : 3,
                    width: 18, height: 18, borderRadius: "50%",
                    background: "white", transition: "left 0.2s",
                  }} />
                </button>
                <span style={{ fontSize: 13, color: "rgba(255,255,255,0.6)" }}>Include timestamps <span style={{ color: "rgba(255,255,255,0.3)" }}>(e.g. [1:23])</span></span>
              </div>
            </div>

            <button
              onClick={extract}
              disabled={!url.trim() || loading}
              style={{
                width: "100%", padding: "14px 0", borderRadius: 12,
                background: (!url.trim() || loading) ? "rgba(99,102,241,0.3)" : "linear-gradient(135deg,#6366f1,#8b5cf6)",
                border: "none", color: "white", fontSize: 15, fontWeight: 700,
                cursor: (!url.trim() || loading) ? "not-allowed" : "pointer",
                transition: "all 0.2s",
              }}
            >
              {loading ? "Extracting transcript…" : "Extract Transcript — Free"}
            </button>
          </div>

          {/* Error */}
          {error && (
            <div style={{ background: "rgba(248,113,113,0.1)", border: "1px solid rgba(248,113,113,0.3)", borderRadius: 12, padding: "14px 18px", marginBottom: 16, color: "#f87171", fontSize: 14 }}>
              {error}
            </div>
          )}

          {/* Results */}
          {result && (
            <div style={{ opacity: visible ? 1 : 0, transform: visible ? "translateY(0)" : "translateY(16px)", transition: "opacity 0.4s ease, transform 0.4s ease" }}>

              {/* Meta bar */}
              <div style={{ ...card, padding: "20px 28px" }}>
                <div style={{ display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: 16 }}>
                  <div>
                    <p style={{ margin: 0, fontSize: 16, fontWeight: 700, color: "white" }}>{result.title}</p>
                    {result.author && <p style={{ margin: "4px 0 0", fontSize: 13, color: "rgba(255,255,255,0.45)" }}>{result.author}</p>}
                  </div>
                  <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "rgba(255,255,255,0.45)" }}>
                      <Hash size={14} />{result.wordCount.toLocaleString()} words
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "rgba(255,255,255,0.45)" }}>
                      <Clock size={14} />{result.readMinutes} min read
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: "rgba(255,255,255,0.45)" }}>
                      <FileText size={14} />Markdown
                    </div>
                  </div>
                </div>
              </div>

              {/* Transcript card */}
              <div style={card}>
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16, flexWrap: "wrap", gap: 10 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <AlignLeft size={16} color="#6366f1" />
                    <span style={{ fontSize: 13, fontWeight: 700, color: "rgba(255,255,255,0.55)", textTransform: "uppercase", letterSpacing: "0.06em" }}>Transcript</span>
                  </div>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button onClick={copy} style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", borderRadius: 8, background: "rgba(99,102,241,0.15)", border: "1px solid rgba(99,102,241,0.3)", color: "#a5b4fc", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>
                      {copied ? <Check size={14} /> : <Copy size={14} />}
                      {copied ? "Copied!" : "Copy Markdown"}
                    </button>
                    <button onClick={download} style={{ display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", borderRadius: 8, background: "rgba(52,211,153,0.1)", border: "1px solid rgba(52,211,153,0.25)", color: "#6ee7b7", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>
                      <Download size={14} />Download .md
                    </button>
                  </div>
                </div>
                <textarea
                  readOnly
                  value={result.markdown}
                  style={{
                    width: "100%", boxSizing: "border-box", minHeight: 320,
                    background: "rgba(0,0,0,0.3)", border: "1px solid rgba(255,255,255,0.07)",
                    borderRadius: 10, padding: "14px 16px",
                    color: "rgba(255,255,255,0.75)", fontSize: 13,
                    fontFamily: "ui-monospace,monospace", lineHeight: 1.7,
                    resize: "vertical", outline: "none",
                  }}
                />
              </div>

              {/* Repurpose tip */}
              <div style={{ background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.15)", borderRadius: 16, padding: "18px 24px", marginBottom: 16, display: "flex", gap: 14, alignItems: "flex-start" }}>
                <span style={{ fontSize: 20 }}>💡</span>
                <div>
                  <p style={{ margin: "0 0 4px", fontWeight: 700, fontSize: 14, color: "#a5b4fc" }}>Repurpose this transcript</p>
                  <p style={{ margin: 0, fontSize: 13, color: "rgba(255,255,255,0.5)", lineHeight: 1.6 }}>
                    Paste into the <Link href="/tools/text-summarizer" style={{ color: "#818cf8", textDecoration: "none" }}>Text Summarizer</Link> for a blog-ready summary, or the <Link href="/tools/paraphrasing-tool" style={{ color: "#818cf8", textDecoration: "none" }}>Paraphrasing Tool</Link> to rewrite sections in your own voice.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* How it works */}
          <div style={{ margin: "56px 0 48px" }}>
            <h2 style={{ fontSize: 26, fontWeight: 800, margin: "0 0 8px" }}>How It Works</h2>
            <p style={{ fontSize: 15, color: "rgba(255,255,255,0.55)", margin: "0 0 28px" }}>Three steps from URL to readable transcript</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 16 }}>
              {[
                { n: "01", icon: "🔗", title: "Paste your URL", body: "Drop in any YouTube link — full URL, short youtu.be link, or just the 11-character video ID. All formats work." },
                { n: "02", icon: "⚡", title: "We fetch the captions", body: "We pull the video's caption track directly from YouTube — no audio processing, no wait time. Works on auto-generated and manual captions." },
                { n: "03", icon: "📄", title: "Download as Markdown", body: "Your transcript arrives formatted with the video title, channel, and full text. Toggle timestamps, then copy or download as a .md file." },
              ].map(s => (
                <div key={s.n} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 18, padding: "22px 24px" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}>
                    <span style={{ fontSize: 11, fontWeight: 800, color: "#818cf8", letterSpacing: "0.08em" }}>{s.n}</span>
                    <span style={{ fontSize: 20 }}>{s.icon}</span>
                  </div>
                  <h3 style={{ fontSize: 15, fontWeight: 700, margin: "0 0 8px" }}>{s.title}</h3>
                  <p style={{ fontSize: 13, color: "rgba(255,255,255,0.45)", margin: 0, lineHeight: 1.6 }}>{s.body}</p>
                </div>
              ))}
            </div>
          </div>

          {/* SEO content */}
          <div style={{ margin: "0 0 56px", padding: "32px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 20 }}>
            <h2 style={{ fontSize: 22, fontWeight: 800, margin: "0 0 16px" }}>Why Extract YouTube Transcripts?</h2>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.5)", lineHeight: 1.8, margin: "0 0 14px" }}>
              YouTube transcripts are one of the most underused content assets on the internet. Every video you watch contains thousands of words of potentially valuable content — but locked inside a format that&apos;s impossible to search, copy, or reuse. A YouTube transcript extractor unlocks that content in seconds.
            </p>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.5)", lineHeight: 1.8, margin: "0 0 14px" }}>
              Content creators use transcripts to repurpose videos into blog posts, newsletters, and social media threads. Researchers extract transcripts to analyse speeches, interviews, and lectures at scale. Students download lecture transcripts to study without rewatching hours of footage. Developers use them to build training datasets.
            </p>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.5)", lineHeight: 1.8, margin: 0 }}>
              Unlike most transcript tools that output raw text, ToolStack formats your transcript as clean Markdown — ready to paste into Notion, Obsidian, a blog post, or an AI tool like ChatGPT or Claude. The optional timestamp mode lets you reference exact moments in the video, making it ideal for journalists, researchers, and editors.
            </p>
          </div>

          {/* FAQ */}
          <div style={{ margin: "0 0 56px" }}>
            <h2 style={{ fontSize: 26, fontWeight: 800, margin: "0 0 24px" }}>Frequently Asked Questions</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {FAQS.map((f, i) => (
                <div key={i} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 16, padding: "20px 24px" }}>
                  <h3 style={{ fontSize: 15, fontWeight: 700, margin: "0 0 8px", color: "white" }}>{f.q}</h3>
                  <p style={{ fontSize: 14, color: "rgba(255,255,255,0.5)", margin: 0, lineHeight: 1.7 }}>{f.a}</p>
                </div>
              ))}
            </div>
          </div>

          <MoreTools currentSlug="youtube-transcript" />
          <AdvertiseGPTBanner />

        </div>
      </div>
    </>
  );
}
